### PR TITLE
Adds proxy support

### LINKED ISSUE #133: Update base shortener to accept proxy settings
`_get()` and `_post()` both use the `requests` library which accept `proxy` as a paramater.  Could we update `base.py` to allow for the optional parameter to be passed to these functions?

I'll volunteer to do the work if you want.

### PR DESCRIPTION
**Pull request by armonge**
Fixes #133

### CODE REVIEW

**Comment by ellisonleao** [comment]
hey @armonge do you think you can add some tests to those changes?

**Comment by armonge** [comment]
Sure thing! I'll work on them over the weekend

**Comment by armonge** [comment]
@ellisonleao any comments?

**Comment by ellisonleao** [comment]
Looks good, thanks @armonge !

**Pull request merged**
